### ISSUE TITLE
Adjust some heading and Modify the Profile

### ISSUE THREAD

**Issue by Smokecode00** [ianlabicani/ncms#47]

**Comment by ianlabicani** [comment]
Change the greeting style to make difference with the Login and Register buttons.
![image](https://github.com/ianlabicani/ncms/assets/91765472/7ff43fa5-65ed-416c-beec-1d322da7c2c9)
![image](https://github.com/ianlabicani/ncms/assets/91765472/588139cc-f05c-4273-9cf0-b9b1c000f3d1)
